#######################################################################################
# A default configuration that will be loaded for all jupyter books
# See the documentation for help and more options: 
# https://jupyterbook.org/customize/config.html

#######################################################################################
# Book settings
title                       : Minería de Textos  # The title of the book. Will be placed in the left navbar.
author                      : Universitat d'Alacant  # The author of the book
copyright                   : "2022"  # Copyright year to be placed in the footer
logo                        : images/logo-master-ca.png  # A path to the book logo
